### ISSUE TITLE
Getting Following exception: Caused by: java.lang.AbstractMethodError: abstract method "java.util.TimeZone ai.api.AIServiceContext.getTimeZone()"

### ISSUE THREAD

**Issue by puliyadivinod** [api-ai/api-ai-android-sdk#29]
03-01 12:28:58.999 6355-9154/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                 Process: com.hexa.helloaction, PID: 6355
                                                 java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.AbstractMethodError: abstract method "java.util.TimeZone ai.api.AIServiceContext.getTimeZone()"
                                                     at ai.api.AIDataService.getTimeZone(AIDataService.java:962)
                                                     at ai.api.AIDataService.request(AIDataService.java:172)
                                                     at ai.api.AIDataService.request(AIDataService.java:148)
                                                     at ai.api.services.GoogleRecognitionServiceImpl$2.doInBackground(GoogleRecognitionServiceImpl.java:166)
                                                     at ai.api.services.GoogleRecognitionServiceImpl$2.doInBackground(GoogleRecognitionServiceImpl.java:158)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by folomeev** [comment]
Please, update Api.Ai Android SDK up to version 2.0.3 and try to reproduce the problem.

**Comment by puliyadivinod** [comment]
thank you so much! it worked.
